import { useEffect,useMemo,useState } from "react";import {Scissors,Upload,Plus,Play,Pause,Download,Volume2,SlidersHorizontal,Radio,Trash2} from "lucide-react";import {useAppStore} from "../lib/AppStore";import {durationOf,exportMix,type AudioClip, type ClipEffect} from "../lib/audioEditor";
export default function AudioEditor(){const store=useAppStore();const[clips,setClips]=useState<AudioClip[]>([]);const[playing,setPlaying]=useState<string|null>(null);const[selected,setSelected]=useState<string|null>(null);const[master,setMaster]=useState(1);
const add=async(blob:Blob,name:string)=>{const d=await durationOf(blob);const id=crypto.randomUUID();setClips(v=>[...v,{id,name,blob,start:v.length?v[v.length-1].start+v[v.length-1].duration:0,trimStart:0,duration:d,volume:1,speed:1,effect:"none"}]);};
const addTrack=(t:any)=>add(t.blob,t.title);const upload=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f)add(f,f.name);e.target.value=""};
const update=(id:string,patch:Partial<AudioClip>)=>setClips(v=>v.map(c=>c.id===id?{...c,...patch}:c));
const selectedClip=clips.find(c=>c.id===selected);const total=Math.max(1,...clips.map(c=>c.start+c.duration/c.speed));
const render=async()=>{if(!clips.length)return;const blob=await exportMix(clips.map(c=>({...c,volume:c.volume*master})));const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="voicemaster-edit.wav";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
useEffect(()=>()=>clips.forEach(c=>URL.revokeObjectURL((c as any).url)),[clips]);
return <section className="mx-auto max-w-6xl space-y-6"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brand">Audio Editor</p><h1 className="font-display text-3xl font-black text-ink">עריכת קריינות</h1><p className="mt-2 text-sm text-mute">טיימליין בסגנון FL Studio: חיתוך, שכבות, מוזיקה, אפקטים ושליטה מדויקת בזמן.</p></div>
<div className="card rounded-[2rem] p-4 sm:p-6"><div className="flex flex-wrap gap-2"><label className="btn btn-outline cursor-pointer"><Upload size={16}/>הוסף מהמחשב<input hidden type="file" accept="audio/*" onChange={upload}/></label><div className="relative"><button className="btn btn-outline"><Plus size={16}/>הוסף מהקריינויות</button><div className="absolute start-0 top-full z-20 mt-2 max-h-64 w-72 overflow-auto rounded-2xl border border-line bg-bg p-2 shadow-xl">{store.tracks.filter(t=>t.kind==="narration").map(t=><button key={t.id} onClick={()=>addTrack(t)} className="block w-full rounded-xl p-3 text-start text-sm hover:bg-soft">{t.title}</button>)}{store.tracks.filter(t=>t.kind==="narration").length===0&&<p className="p-3 text-xs text-mute">אין קריינויות זמינות</p>}</div></div><button onClick={render} disabled={!clips.length} className="btn btn-primary ms-auto"><Download size={16}/>ייצוא WAV</button></div>
<div className="mt-6 overflow-x-auto rounded-2xl border border-line bg-[#111318] p-4"><div className="relative min-w-[900px]" style={{height:Math.max(220,clips.length*92)}}><div className="absolute inset-x-0 top-0 flex justify-between border-b border-white/10 pb-2 text-[10px] text-white/50">{[0,.25,.5,.75,1].map(x=><span key={x}>{(total*x).toFixed(1)}s</span>)}</div>{clips.map((c,i)=><div key={c.id} onClick={()=>setSelected(c.id)} className={"absolute h-16 cursor-pointer rounded-xl border p-2 text-white "+(selected===c.id?"border-brand bg-brand/20":"border-white/10 bg-white/5")} style={{left:`${c.start/total*100}%`,width:`${Math.max(8,c.duration/c.speed/total*100)}%`,top:35+i*82}}><div className="truncate text-xs font-bold">{c.name}</div><div className="mt-1 text-[10px] opacity-60">{c.effect} · {c.volume.toFixed(1)}x</div></div>)}</div></div></div>
{selectedClip&&<div className="card rounded-[2rem] p-5 sm:p-7"><div className="mb-5 flex items-center gap-2"><SlidersHorizontal className="text-brand"/><h2 className="font-display text-xl font-black">עריכת הקטע</h2></div><div className="grid gap-5 md:grid-cols-2"><div><label className="label">מיקום על ציר הזמן: {selectedClip.start.toFixed(1)} שנ׳</label><input type="range" min="0" max={Math.max(60,total+30)} step=".1" value={selectedClip.start} onChange={e=>update(selectedClip.id,{start:+e.target.value})} className="w-full"/></div><div><label className="label">חיתוך התחלה: {selectedClip.trimStart.toFixed(1)} שנ׳</label><input type="range" min="0" max={Math.max(0,selectedClip.duration-.1)} step=".1" value={selectedClip.trimStart} onChange={e=>update(selectedClip.id,{trimStart:+e.target.value,duration:Math.max(.1,selectedClip.duration-selectedClip.trimStart)})} className="w-full"/></div><div><label className="label">עוצמה: {Math.round(selectedClip.volume*100)}%</label><input type="range" min="0" max="1.5" step=".01" value={selectedClip.volume} onChange={e=>update(selectedClip.id,{volume:+e.target.value})} className="w-full"/></div><div><label className="label">מהירות: {selectedClip.speed.toFixed(2)}x</label><input type="range" min=".5" max="2" step=".01" value={selectedClip.speed} onChange={e=>update(selectedClip.id,{speed:+e.target.value})} className="w-full"/></div><div><label className="label">אפקט</label><select value={selectedClip.effect} onChange={e=>update(selectedClip.id,{effect:e.target.value as ClipEffect})} className="field w-full"><option value="none">ללא</option><option value="echo">הד / Echo</option><option value="reverb">הדהוד / Reverb</option><option value="fade">Fade</option></select></div><div className="flex items-end"><button onClick={()=>setClips(v=>v.filter(c=>c.id!==selectedClip.id))} className="btn btn-outline text-danger"><Trash2 size={16}/>הסר מהטיימליין</button></div></div></div>}
<div className="card rounded-[2rem] p-5"><div className="flex items-center gap-3"><Volume2 size={18}/><b>עוצמת המיקס</b><input type="range" min="0" max="1.5" step=".01" value={master} onChange={e=>setMaster(+e.target.value)} className="max-w-xs flex-1"/></div><p className="mt-2 text-xs text-mute">אפשר להוסיף כמה שכבות שמע, למקם אותן בזמן ולייצא מיקס אחד.</p></div></section>}
